########### Android Lanes ###########

platform :android do
  desc 'Build the Android release.'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'release', project_dir: 'android/')
  end

  desc 'Build and upload to App Center.'
  lane :beta do
    build
    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      app_name: ENV["APPCENTER_APP_NAME"],
      destinations: ENV["APPCENTER_DESTINATIONS"],
      apk: "./android/app/build/outputs/apk/release/app-universal-release.apk"
      )
  end
end